#!/bin/bash
version=0.1
echo "macnod/predictor-api:$version"
docker build -qf docker/Dockerfile-api -t macnod/predictor-api:$version -t macnod/predictor-api:latest .
echo
echo "macnod/predictor-train:$version"
docker build -qf docker/Dockerfile-train -t macnod/predictor-train:$version -t macnod/predictor-train:latest .
echo
