#!/bin/bash

#
# Run this from the repo's root directory!
#
# Remember to run source predictor-venv/bin/activate before running these tests.
#

if [ -z "$1" ]; then
    echo "Running all tests..."
    python -m unittest discover -s tests -v
else
    echo "Running test: $1"
    python -m unittest tests.$1 -v
fi
