apiVersion: batch/v1
kind: CronJob
metadata:
  name: predictor-train-cron
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.predictorTrain.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: predictor-train
        spec:
          containers:
            - name: predictor-train
              image: {{ .Values.predictorTrain.schedule }}
              imagePullPolicy: Always
              env:
                - name: PREDICTOR_LOG_LEVEL
                  value: "info"
                - name: PREDICTOR_DB_HOST
                  value: "postgres-service"
                - name: PREDICTOR_DB_PORT
                  value: "5432"
          restartPolicy: Never
