apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-train
  labels:
    app: predictor-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor-train
  template:
    metadata:
      labels:
        app: predictor-train
    spec:
      containers:
        - name: predictor-train
          image: macnod/predictor-train:latest
          imagePullPolicy: Always
          env:
            - name: PREDICTOR_DB_HOST
              value: "postgres-service"
            - name: PREDICTOR_DB_PORT
              value: "5432"
            - name: PREDICTOR_LOG_LEVEL
              value: "info"
      restartPolicy: Always
