apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-06-26T03:32:07Z"
  generation: 1
  labels:
    app: predictor
  name: predictor
  namespace: default
  resourceVersion: "29351"
  uid: 32d388ae-c013-4afd-a192-c0f4d093f1d9
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: predictor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: predictor
    spec:
      containers:
      - image: macnod/predictor:latest
        imagePullPolicy: Always
        name: predictor
        env:
          - name: PREDICTOR_API_DB_HOST
            value: "postgres-service"
          - name: PREDICTOR_API_DB_PORT
            value: "5432"
          - name: PREDICTOR_API_LOG_LEVEL
            value: "info"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
