apiVersion: v1
kind: Service
metadata:
  name: predictor-service
  namespace: {{ .Values.namespace }}
  labels:
    app: predictor-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.loadBalancer.port }}
      targetPort: 8000
  selector:
    app: predictor-api
