apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-api
  namespace: {{ .Values.namespace }}
  labels:
    app: predictor-api
spec:
  replicas: {{ .Values.predictorApi.replicas }}
  selector:
    matchLabels:
      app: predictor-api
  template:
    metadata:
      labels:
        app: predictor-api
    spec:
      containers:
        - name: predictor-api
          image: {{ .Values.predictorApi.image }}
          imagePullPolicy: Always
          env:
            - name: PREDICTOR_API_DB_HOST
              value: "postgres-service"
            - name: PREDICTOR_API_DB_PORT
              value: "5432"
            - name: PREDICTOR_API_LOG_LEVEL
              value: "info"
      restartPolicy: Always
