apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-api
  namespace: {{ .Values.namespace }}
  labels:
    app: predictor-api
spec:
  replicas: {{ .Values.predictorApi.replicas }}
  selector:
    matchLabels:
      app: predictor-api
  template:
    metadata:
      labels:
        app: predictor-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U jobs-user; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              echo "PostgreSQL is ready!"
          env:
            - name: PGPASSWORD
              value: "jobs-user-password"
      containers:
        - name: predictor-api
          image: {{ .Values.predictorApi.image }}
          imagePullPolicy: Always
          env:
            - name: PREDICTOR_API_DB_HOST
              value: "postgres-service"
            - name: PREDICTOR_API_DB_PORT
              value: "5432"
            - name: PREDICTOR_API_LOG_LEVEL
              value: "info"
      restartPolicy: Always
