# predictor
# :host = http://20.228.64.1

# predictor production
:host = http://20.253.215.165

# Check health
GET :host/health

# Get a count of the jobs in the job_history table
GET :host/job-history-length

# Insert some bogus job history records
POST :host/insert-bogus-job-history
Content-Type: application/json

{
  "count": 1000
}

# Delete all job history records
POST :host/delete-all-records

# Insert a new job
POST :host/new-job
Content-Type: application/json

{
  "start_at": "2025-06-26 12:03:00",
  "record_count": 900
}

# Train model
POST :host/train

# Predict
POST :host/predict

# Shutdown
POST :host/shutdown
