name: CI

on:
  push:
    branches:
      - staging
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python modules
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          ./run-tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      # Sadly, the repo is using Helm 2.17.0, so we have to stick to
      # setup-helm@v1. The newer ones want Helm 3+
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v2.17.0'

      - name: Configure Kubernetes credentials
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            kubectl apply -f kube/predictor-production.yaml -n predictor-production
          else
            kubectl apply -f kube/predictor-staging.yaml -n predictor-staging
          fi
